import React, { useState } from "react";
import { FaFileDownload } from "react-icons/fa";
import jsPDF from 'jspdf';

const StockPDF = ({ allProducts }) => {

    const [isGenerating, setIsGenerating] = useState(false);

    const generateProductPDF = async () => {
        try {

            setIsGenerating(true);

            //Create new PDF
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });

            //Date Formatting
            const currentDate = new Date();
            const dateFormatted = currentDate.toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            });

            //Company Header
            pdf.setFontSize(20);
            pdf.setTextColor(50, 50, 50);
            pdf.text("Product Inventory Report", 20, 20);

            pdf.setFontSize(10);
            pdf.setTextColor(100, 100, 100);
            pdf.text(`Date: ${dateFormatted}`, 20, 30);
            pdf.text(`Generated By: Admin`, 20, 35);

            //Company Info
            pdf.setFontSize(14);
            pdf.setTextColor(50, 50, 50);
            pdf.text("META Computers", 150, 20);
            pdf.setFontSize(10);
            pdf.setTextColor(100, 100, 100);
            pdf.text("142/1/1, Kotugoda Road, Seeduwa,", 150, 25);
            pdf.text("Sri Lanka", 150, 30);
            pdf.text("+94 77 067 0436", 150, 35);

            //Table Header
            let y = 50;
            pdf.setFillColor(240, 240, 240);
            pdf.rect(20, y, 170, 7, 'F');
            pdf.setFontSize(10);
            pdf.setTextColor(50, 50, 50);
            pdf.text("Product Name", 22, y + 5);
            pdf.text("Brand", 75, y + 5);
            pdf.text("Category", 105, y + 5);
            pdf.text("Quantity", 135, y + 5);
            // pdf.text("Price (LKR)", 160, y + 5);

            //Table content
            y += 10;
            allProducts.forEach((product, index) => {

                if (y > 270) {
                    pdf.addPage();
                    y = 20;

                    //Adding header to new page
                    pdf.setFillColor(240, 240, 240);
                    pdf.rect(20, y, 170, 7, 'F');
                    pdf.setFontSize(10);
                    pdf.setTextColor(50, 50, 50);
                    pdf.text("Product Name", 22, y + 5);
                    pdf.text("Brand", 75, y + 5);
                    pdf.text("Category", 105, y + 5);
                    pdf.text("Quantity", 135, y + 5);
                    // pdf.text("Price (LKR)", 160, y + 5);

                    y += 10;
                }

                //Alternate row coloring
                if (index % 2 === 0) {
                    pdf.setFillColor(245, 245, 245);
                    pdf.rect(20, y - 3, 170, 7, 'F')
                }

                pdf.setTextColor(70, 70, 70);

                //if product name too long
                const displayName = product.name.length > 25 ?
                    product.name.substring(0, 22) + '...' :
                    product.name;

                pdf.text(displayName, 22, y);
                pdf.text(product.brand || "N/A", 75, y);
                pdf.text(product.category || "N/A", 105, y);
                pdf.text(product.quantity?.toString() || "0", 135, y);
                // pdf.text(product.price?.toLocaleString() || "0", 160, y);

                y += 7;
            });

            //Summary
            y += 10;
            pdf.setDrawColor(200, 200, 200);
            pdf.line(20, y, 190, y);

            y += 10;
            pdf.setFontSize(11);
            pdf.setTextColor(50, 50, 50);
            pdf.text(`Total Products: ${allProducts.length}`, 20, y);

            //Footer
            const pageCount = pdf.internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                pdf.setPage(i);
                pdf.setFontSize(8);
                pdf.setTextColor(150, 150, 150);
                pdf.text(
                    `Page ${i} of ${pageCount} - Generated on ${dateFormatted}`,
                    pdf.internal.pageSize.getWidth() / 2,
                    pdf.internal.pageSize.getHeight() - 10,
                    { align: 'center' }
                );
            }

            //PDF save
            pdf.save(`Product_Inventory_${new Date().toISOString().split('T')[0]}.pdf`);
            console.log("PDF generated successfully");
            setIsGenerating(false);

        } catch (error) {
            console.error("PDF generation error: ", error);
            alert("Failed to generate PDF...");
            setIsGenerating(false);
        }
    };

    return (
        <button 
            className={`bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition flex items-center ${isGenerating ? 'opacity-70 cursor-not-allowed' : ''}`}
            onClick = {generateProductPDF}
            disabled = {isGenerating}
        >

            <FaFileDownload className="mr-2"/>
            {isGenerating ? 'Generating PDF...' : 'Download Product List'}
        </button >
    );

};

export default StockPDF;